export enum GATEWAY {
  FIB = "FIB",
  ZAIN = "ZAIN",
  ASIA_PAY = "ASIA_PAY",
  FAST_PAY = "FAST_PAY",
  NASS_WALLET = "NASS_WALLET",
  CREDIT_CARD = "CREDIT_CARD",
}

export enum PAYMENT_STATUS {
  TIMED_OUT = "TIMED_OUT",
  PENDING = "PENDING",
  PAID = "PAID",
  CANCELED = "CANCELED",
  FAILED = "FAILED",
  SETTLED = "SETTLED",
}
